<?php

declare(strict_types=1);

namespace GarbuzIvan\LaravelGeneratorPackage\Test\Form;

use Exception;
use GarbuzIvan\LaravelGeneratorPackage\Form\Field;
use PHPUnit\Framework\TestCase;

class FieldTest extends TestCase
{
    protected Field $field;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->field = new Field();
    }

    public function testFieldInit()
    {
        $field = $this->field->text('title', 'Title');
        $this->assertIsBool($field->getColumn() == 'title');
        $this->assertIsBool($field->getLabel() == 'Title');
    }

    public function testFieldInitExceptionTypeColumn()
    {
        $this->field->text(123, 'Title');
        $this->expectException(Exception::class);
    }

    public function testFieldInitExceptionMaskColumn()
    {
        $this->field->text('проверка', 'Title');
        $this->expectException(Exception::class);
    }
}
